version: '3'
services:
    database:
        build:
            context: ./docker/mariadb
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
            TZ: '${TIMEZONE}'
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./docker/mariadb/data:/var/lib/mysql
        command: mysqld --sql_mode="" --character-set-server=latin1 --collation-server=latin1_swedish_ci --innodb-flush-log-at-trx-commit=0
        restart: on-failure
    webapp:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        volumes:
            - './app/SembrandoConAmor/:/usr/src/app'
        user: ${LOCAL_USER}:${LOCAL_USER}
        privileged: true
    nginx:
        image: nginx:1.19.0-alpine
        restart: on-failure
        volumes:
            - './app/SembrandoConAmor/public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '${NGINX_PORT}:80'
        depends_on:
            - webapp
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - 'database'
        ports:
            - '${ADMINER_PORT}:80'
        environment:
            MYSQL_USERNAME: ${DATABASE_USER}
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            PMA_HOST: database
        restart: on-failure